tap "1password/tap"
tap "charmbracelet/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "robotsandpencils/made"
tap "romkatv/powerlevel10k"
brew "sqlite"
brew "autopep8"
brew "bat"
brew "black"
brew "clang-format"
brew "cmake"
brew "curl"
brew "node"
brew "eleventy"
brew "openjpeg"
brew "ffmpeg"
brew "flake8"
brew "gcc"
brew "gh"
brew "git"
brew "gnupg"
brew "openjdk"
brew "python@3.10"
brew "google-java-format"
brew "graphviz"
brew "howdoi"
brew "htop"
brew "make"
brew "mas"
brew "protobuf"
brew "mysql", restart_service: true
brew "ncdu"
brew "netlify-cli"
brew "numpy"
brew "pandoc"
brew "pdfgrep"
brew "prettier"
brew "pygments"
brew "speedtest-cli"
brew "stylua"
brew "thefuck"
brew "tldr"
brew "tmux"
brew "trash-cli"
brew "tree"
brew "tree-sitter"
brew "ttyd"
brew "vim"
brew "wget"
brew "yarn"
brew "yt-dlp"
brew "zsh"
brew "charmbracelet/tap/vhs"
brew "romkatv/powerlevel10k/powerlevel10k"
cask "1password"
cask "1password-cli"
cask "aerial"
cask "alfred"
cask "anki"
cask "backblaze"
cask "brave-browser"
cask "darktable"
cask "diffusionbee"
cask "discord"
cask "drawio"
cask "dropbox"
cask "eloston-chromium"
cask "endnote"
cask "exodus"
cask "figma"
cask "firefox"
cask "flux"
cask "font-fira-code-nerd-font"
cask "font-fira-mono-nerd-font"
cask "font-ia-writer-duo"
cask "font-ia-writer-duospace"
cask "font-ia-writer-mono"
cask "font-ia-writer-quattro"
cask "font-lato"
cask "font-sacramento"
cask "github"
cask "google-chrome"
cask "google-drive"
cask "google-earth-pro"
cask "grammarly"
cask "iina"
cask "iterm2"
cask "kindle"
cask "kitty"
cask "logi-options-plus"
cask "mactex"
cask "messenger"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "microsoft-teams"
cask "minecraft"
cask "monodraw"
cask "moom"
cask "mos"
cask "notion"
cask "numi"
cask "obsidian"
cask "pdfpen"
cask "raspberry-pi-imager"
cask "rocket"
cask "selfcontrol"
cask "sf-symbols"
cask "slack"
cask "soundsource"
cask "spotify"
cask "steam"
cask "the-archive"
cask "todoist"
cask "visual-studio-code"
cask "vlc"
cask "vmware-horizon-client"
cask "whatsapp"
cask "xcodes"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "Accelerate", id: 1459809092
mas "Amphetamine", id: 937984704
mas "Dark Reader for Safari", id: 1438243180
mas "Developer", id: 640199958
mas "Drafts", id: 1435957248
mas "GarageBand", id: 682658836
mas "Hand Mirror", id: 1502839586
mas "Horo", id: 1437226581
mas "iA Writer", id: 775737590
mas "Instapaper Save", id: 1481302432
mas "Keynote", id: 409183694
mas "MindNode", id: 1289197285
mas "Negative", id: 1378123825
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Paprika Recipe Manager 3", id: 1303222628
mas "PayPal Honey", id: 1472777122
mas "Reeder", id: 1529448980
mas "Spark", id: 1176895641
mas "StopTheMadness", id: 1376402589
mas "Things", id: 904280696
mas "Timery", id: 1425368544
